import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-pink-900 min-h-screen flex flex-col`}
  >
    {/* Navbar stays at the top */}
    <Navbar />

    {/* Main content */}
    <main className="flex-1 container mx-auto px-6 py-10">
      {children}
    </main>
  </body>
</html>

  );
}
